version: "3.8"
services:
  development:
      container_name: node
      build: 
        context: ./
        dockerfile: Dockerfile
      volumes:
       - ./:/app
       - /node_modules
      restart: always
      ports: 
        - "8080:3000"
      environment:
        CHOKIDAR_USEPOLLING: 'true'
