export const dachzeileToRessort = {
    // "": "keine Zuordnung",
    // "null": "keine Zuordnung",
    // "Bürgerräte": "keine Zuordnung",
    // "Geschäftsordnung": "keine Zuordnung",
    // "Hauptausschuss": "keine Zuordnung",
    // "Immunität": "keine Zuordnung",
    // "Kultur": "keine Zuordnung",
    // "Medien": "keine Zuordnung",
    // "Menschenrechte": "keine Zuordnung",
    // "Parlament": "keine Zuordnung",
    // "Parlamentarischer Beirat für nachhaltige Entwicklung": "keine Zuordnung",
    // "Parlamentarisches Kontrollgremium": "keine Zuordnung",
    // "Petitionen": "keine Zuordnung",
    // "Regierungserklärung": "keine Zuordnung",
    // "1. Untersuchungsausschuss": "keine Zuordnung",
    // "2. Untersuchungsausschuss": "keine Zuordnung",
    // "3. Untersuchungsausschuss": "keine Zuordnung",
    // "4. Untersuchungsausschuss": "keine Zuordnung",
    // "5. Untersuchungsausschuss": "keine Zuordnung",
    // "Wahlprüfung": "keine Zuordnung",
    // "Wahlrechtskomission": "keine Zuordnung",
    "Arbeit": "Arbeit",
    "Auswärtiges": "Außenpolitik",
    "Bau": "Wohnungsbau",
    "Bauwesen": "Wohnungsbau",
    "Bildung": "Bildung und Forschung",
    "Digitale Agenda": "Verkehr und Digitalisierung",
    "Digitale Infrastruktur": "Verkehr und Digitalisierung",
    "Digitales": "Verkehr und Digitalisierung",
    "Energie": "Wirtschaft",
    "Entwicklung": "Entwicklung",
    "Ernährung": "Landwirtschaft",
    "Enquete-Komission Künstliche Intelligenz": "Verkehr und Digitalisierung",
    "Enquete-Komission Berufliche Bildung": "Bildung und Forschung",
    "Europäische Union": "Bildung und Forschung",
    "Familie": "Familie",
    "Finanzen": "Finanzen",
    "Forschung": "Bildung und Forschung",
    "Frauen": "Familie",
    "Gesundheit": "Gesundheit",
    "Haushalt": "Finanzen",
    "Heimat": "Innenpolitik",
    "Humanitäre Hilfe": "Außenpolitik",
    "Inneres": "Innenpolitik",
    "Jugend": "Familie",
    "Kinderkomission": "Familie",
    "Kommunen": "Innenpolitik",
    "Klimaschutz": "Wirtschaft",
    "Landwirtschaft": "Landwirtschaft",
    "Naturschutz": "Umwelt",
    "Nukleare Sicherheit": "Umwelt",
    "Reaktorsicherheit": "Wirtschaft",
    "Recht": "Justiz",
    "Senioren": "Familie",
    "Soziales": "Arbeit",
    "Sport": "Innenpolitik",
    "Stadtentwicklung": "Wohnungsbau",
    "Städtebau": "Wohnungsbau",
    "Wohnen": "Wohnungsbau",
    "Technologiefolgenabschätzung": "Verkehr und Digitalisierung",
    "Tourismus": "Wirtschaft",
    "Umwelt": "Umwelt",
    "Verbraucherschutz": "Umwelt",
    "Verkehr": "Verkehr und Digitalisierung",
    "Verteidigung": "Verteidigung",
    "Verteidigung/Untersuchungsausschuss": "Verteidigung",
    "Wirtschaft": "Wirtschaft",
    "Wirtschaftliche Zusammenarbeit": "Entwicklung "
}

